/* eslint-disable lingui/no-unlocalized-strings */
export const tempMockLayoutData = {
  id: "cly4hzgaz0001rjzc1zz5gkcv",
  title: "lalalal",
  slug: "lalalal",
  data: {
    basics: {
      name: "Johe",
      headline: "",
      email: "test_10@gmail.com",
      phone: "",
      location: "",
      url: {
        label: "",
        href: "",
      },
      customFields: [],
      picture: {
        url: "",
        size: 64,
        aspectRatio: 1,
        borderRadius: 0,
        effects: {
          hidden: false,
          border: false,
          grayscale: false,
        },
      },
    },
    sections: {
      summary: {
        name: "Summary",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "summary",
        content: "",
      },
      awards: {
        name: "Awards",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "awards",
        items: [],
      },
      certifications: {
        name: "Certifications",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "certifications",
        items: [],
      },
      education: {
        name: "Education",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "education",
        items: [],
      },
      experience: {
        name: "Experience",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "experience",
        items: [],
      },
      volunteer: {
        name: "Volunteering",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "volunteer",
        items: [],
      },
      interests: {
        name: "Interests",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "interests",
        items: [],
      },
      languages: {
        name: "Languages",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "languages",
        items: [],
      },
      profiles: {
        name: "Profiles",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "profiles",
        items: [],
      },
      projects: {
        name: "Projects",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "projects",
        items: [],
      },
      publications: {
        name: "Publications",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "publications",
        items: [],
      },
      references: {
        name: "References",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "references",
        items: [],
      },
      skills: {
        name: "Skills",
        columns: 1,
        separateLinks: true,
        visible: true,
        id: "skills",
        items: [],
      },
      custom: {},
    },
    metadata: {
      template: "rhyhorn",
      layout: [
        [
          ["profiles", "experience", "summary", "education", "projects", "volunteer", "references"],
          ["skills", "interests", "certifications", "awards", "publications", "languages"],
        ],
      ],
      css: {
        value: ".section {\n\toutline: 1px solid #000;\n\toutline-offset: 4px;\n}",
        visible: false,
      },
      page: {
        margin: 18,
        format: "a4",
        options: {
          breakLine: true,
          pageNumbers: true,
        },
      },
      theme: {
        background: "#ffffff",
        text: "#000000",
        primary: "#dc2626",
      },
      typography: {
        font: {
          family: "IBM Plex Serif",
          subset: "latin",
          variants: ["regular", "italic", "600"],
          size: 14,
        },
        lineHeight: 1.5,
        hideIcons: false,
        underlineLinks: true,
      },
      notes: "",
    },
  },
  visibility: "private",
  locked: false,
  userId: "clxyuorcn0002kt6xnocwwgfq",
  createdAt: "2024-07-02T14:21:57.707Z",
  updatedAt: "2024-07-03T04:20:57.359Z",
};

export const menuItems = [
  {
    key: "sub1",
    label: "軟體/工程師",
    children: [
      { key: "1", label: "iOS工程師" },
      { key: "2", label: "Android工程師" },
      { key: "3", label: "前端工程師" },
      { key: "4", label: "後端工程師" },
      { key: "5", label: "系統分析師" },
      { key: "6", label: "測試工程師" },
      { key: "7", label: "資訊安全測試工程師" },
      { key: "8", label: "軟體專案主管" },
      { key: "9", label: "演算法工程師" },
      { key: "10", label: "軟體工程師" },
      { key: "11", label: "區塊鏈工程師" },
    ],
  },
  {
    key: "sub2",
    label: "業務",
    children: [
      { key: "12", label: "國內業務" },
      { key: "13", label: "國外業務" },
      { key: "14", label: "銷售業務" },
      { key: "15", label: "通路開發" },
      { key: "16", label: "專案業務" },
      { key: "17", label: "汽車銷售" },
      { key: "18", label: "內勤業務" },
      { key: "19", label: "醫藥業務" },
      { key: "20", label: "廣告業務" },
      { key: "21", label: "業務分析師" },
      { key: "22", label: "客服經理" },
      { key: "23", label: "客戶經理" },
      { key: "24", label: "市場開發業務" },
      { key: "25", label: "營運業務" },
    ],
  },
  {
    key: "sub3",
    label: "行銷",
    children: [
      { key: "26", label: "行銷企劃" },
      { key: "27", label: "行銷主管" },
      { key: "28", label: "行銷助理" },
      { key: "29", label: "社群編輯" },
      { key: "30", label: "內容行銷" },
      { key: "31", label: "活動企劃" },
      { key: "32", label: "廣告企劃" },
      { key: "33", label: "廣告投放" },
      { key: "34", label: "SEO 內容行銷" },
      { key: "35", label: "電商行銷" },
      { key: "36", label: "市場分析" },
      { key: "37", label: "媒體公關" },
      { key: "38", label: "公關助理" },
      { key: "39", label: "行銷總監" },
    ],
  },
  {
    key: "sub4",
    label: "設計",
    children: [
      { key: "40", label: "2D/平面廣告設計師" },
      { key: "41", label: "3D遊戲/角色設計師" },
      { key: "42", label: "BI/BX 設計師" },
      { key: "43", label: "創意指導" },
      { key: "44", label: "藝術總監" },
      { key: "45", label: "編輯設計師" },
      { key: "46", label: "展覽設計師" },
      { key: "47", label: "時裝設計師" },
      { key: "48", label: "室內設計師" },
      { key: "49", label: "景觀設計師" },
      { key: "50", label: "工業設計師" },
      { key: "51", label: "媒體公關" },
      { key: "52", label: "UI/UX 設計師" },
      { key: "53", label: "網站設計師" },
    ],
  },
  {
    key: "sub5",
    label: "AI/數據",
    children: [
      { key: "54", label: "資料科學家" },
      { key: "55", label: "資料工程師" },
      { key: "56", label: "AI工程師" },
      { key: "57", label: "ML工程師" },
      { key: "58", label: "BI工程師" },
      { key: "59", label: "資料分析師" },
      { key: "60", label: "商業分析師" },
    ],
  },
];
